blank_issues_enabled: false
contact_links:
  - name: ğŸ§ Miracles Journey æ•´åˆåŒ…å®˜æ–¹QQç¾¤
    url: https://qm.qq.com/q/LztDsb7qg4
    about: è®°å¾—è¦åŠ ç¾¤å•Š! ä¸€å®šè¦åŠ å•Š!

  - name: ğŸ“œ Miracles Journey Wiki
    url: https://miraclesjourney.qianf.fun/
    about: å®˜æ–¹Wiki, æœ‰ä¸€äº›æ•™ç¨‹å’Œå¸¸è§é—®é¢˜è§£ç­”
