
[Gameplay]
	#Skyjade tools will be enchantable
	"Skyjade Enchant" = false
	#Always Enable halloween content, excluding the halloween slider
	"Always Enable Halloween Content" = false
	#The item dropped when the Slider is defeated flawlessly, set value to null (with quotation marks!) to disable flawless boss drops from the slider
	"Slider Flawless Boss Drop" = "deep_aether:slider_eye"
	#The item dropped when the Valkyrie Queen is defeated flawlessly, set value to null (with quotation marks!) to disable flawless boss drops from the Valkyrie Queen
	"Valkyrie Queen Flawless Boss Drop" = "deep_aether:medal_of_honor"
	#The item dropped when the Sun Spirit is defeated flawlessly, set value to null (with quotation marks!) to disable flawless boss drops from the Sun Spirit
	"Sun Spirit Flawless Boss Drop" = "deep_aether:sun_core"

[Biomes]
	#The weighting of Deep Aether regions in the aether
	"Deep Aether Biome Weight" = 20
	#Disables Roseroot Forest biomes from generating. Might make some content unobtainable
	"Disable Roseroot Forest Biomes" = false
	#Disables Yagroot Swamp biomes from generating. Might make some content unobtainable
	"Disable Yagroot Swamp Biomes" = false
	#Disables Golden Heights biomes from generating. Might make some content unobtainable
	"Disable Golden Heights Biomes" = false
	#Disables Aerlavender Fields biomes from generating. Might make some content unobtainable
	"Disable Aerlavender Fields Biomes" = false

