
#Faction Craft Mod Config
[mod_config]
	#Enables experimental features 
	#Default false
	enableExperimentalFeatures = false

#Factions
[factions]
	#A list of disabled factions. 
	#Default: The internal skeleton test faction. 
	disabledFactions = ["faction_craft:skeleton_test", "faction_craft:slime_test"]
	#Enables default faction for entities. Turning this off might cause some mobs to no longer attack villagers. 
	#Default true
	enableDefaultFaction = true
	#Enables Gaia faction for entities. Turning this off might cause some weirdness with factions, but can fix unforeseen bugs. 
	#Default true
	enableGaiaFaction = true

#Standard Raid Calculations
[standard_raid_calculations]
	#Disables faction raids 
	#Default false
	disableFactionRaids = false
	#The number of waves for Easy difficulty. 
	#Default 2
	#Range: 1 ~ 9999
	numberWavesEasy = 2
	#The number of waves for Normal difficulty. 
	#Default 4
	#Range: 1 ~ 9999
	numberWavesNormal = 4
	#The number of waves for Hard difficulty. 
	#Default 6
	#Range: 1 ~ 9999
	numberWavesHard = 6
	#The max number of waves. 
	#Default 10
	#Range: 1 ~ 9999
	maxNumberWaves = 10
	#The multiplier for the target strength for the first wave. 
	#1.0 disables Starting wave multiplier. Default 0.65
	#Range: -100.0 ~ 100.0
	baseWaveMultiplier = 0.65
	#The amount the multiplier for the target strength increases per wave. 
	#0.0 removes target growth per wave. Default 0.15
	#Range: -100.0 ~ 100.0
	multiplierIncreasePerWave = 0.15
	#The multiplier per bad omen level for the target strength. 
	#0.0 removes increase Bad Omen impact. Default 0.1
	#Range: -100.0 ~ 100.0
	multiplierIncreasePerBadOmen = 0.1
	#The amount the the target strength can fluctuate per wave. 
	#Default 0.1
	#Range: -100.0 ~ 100.0
	waveTargetStrengthSpread = 0.1
	#The multiplier applied to target strength for Easy difficulty. 
	#0.0 disables difficulty based multipliers. Default -0.1
	#Range: -100.0 ~ 100.0
	targetStrengthDifficultyMultiplierEasy = -0.1
	#The multiplier applied to target strength for Normal difficulty. 
	#0.0 disables difficulty based multipliers. Default 0.0
	#Range: -100.0 ~ 100.0
	targetStrengthDifficultyMultiplierNormal = 0.0
	#The multiplier applied to target strength for Hard difficulty. 
	#0.0 disables difficulty based multipliers. Default 1.1
	#Range: -100.0 ~ 100.0
	targetStrengthDifficultyMultiplierHard = 0.1

#Village Raid Target Calculations
[village_raid_target_calculations]
	#Applied to the target strength of the village 
	#Multiplies the target strength and rounds down. 
	#Vanilla villages have a target strength between 10 and 20. Default 1.0F
	#Range: 0.0 ~ 100.0
	villageRaidTargetStrengthMultiplier = 1.0
	#Applied to the target strength of the village 
	#Additional waves is calulcated by applying this value to target strength. 
	#Vanilla villages have a target strength between 50 and 100. Default 0.01F
	#Range: 0.0 ~ 10.0
	villageRaidAdditionalWaveChance = 0.01
	#The amount that 1 villager adds to the strength of a village. 
	#Default 5
	#Range: 0 ~ 9999
	villageRaidVillagerWeight = 5
	#The amount that 1 Iron Golem adds to the strength of a village. 
	#Default 15
	#Range: 0 ~ 9999
	villageRaidIronGolemWeight = 15
	#The amount that 1 Guard Villager adds to the strength of a village. 
	#Default 7
	#Range: 0 ~ 9999
	villageRaidGuardVillagerWeight = 7

#Player Raid Target Calculations
[player_raid_target_calculations]
	#Base target strength of the player 
	#Default 70
	#Range: 0 ~ 9999
	playerRaidTargetBaseStrength = 70
	#Applied to the target strength of the player 
	#Multiplies the target strength and rounds down. Default 1.0F
	#Range: 0.0 ~ 100.0
	playerRaidTargetStrengthMultiplier = 1.0

#Patroller Config
[patroller_config]
	#Disables faction patrols 
	#Default false
	disableFactionPatrols = false
	#Disables vanilla patrols (and such, vanilla raids) 
	#Default true
	disableVanillaPatrols = true
	#ingame daytime before patrols start spawning. 
	#Vanilla is 24000L equivalent of 5days. Default 24000L
	#Range: 0 ~ 9999999999
	patrolDaytimeBeforeSpawning = 24000
	#This value plus the variable version together make up the time between two spawn attempts. 
	#Vanilla default 12000, Default 6000
	#Range: 0 ~ 999999999
	patrolTickDelayBetweenSpawnAttempts = 9000
	#A random value between 0 and this value is added to the static delay to determine total delay. 
	#Vanilla default is 1200. Default 1200
	#Range: 0 ~ 999999999
	patrolVariableTickDelayBetweenSpawnAttempts = 1200
	#The chance a patrol spawns on a spawn attempt. 
	#Vanilla default is 0.2 Default 0.3
	#Range: 0.0 ~ 1.0
	patrolSpawnChanceOnSpawnAttempt = 0.3

#Faction Battle Config
[faction_battle_config]
	#Disables faction battles 
	#Default false
	disableFactionBattles = false
	#ingame daytime before battles start spawning. 
	#Vanilla is 4800L equivalent of 1days. Default 48000L
	#Range: 0 ~ 9999999999
	battleDaytimeBeforeSpawning = 48000
	#This value plus the variable version together make up the time between two spawn attempts. 
	#Default 18000
	#Range: 0 ~ 999999999
	battleTickDelayBetweenSpawnAttempts = 18000
	#A random value between 0 and this value is added to the static delay to determine total delay. 
	#Default 2400
	#Range: 0 ~ 999999999
	battleVariableTickDelayBetweenSpawnAttempts = 2400
	#The chance a battle spawns on a spawn attempt. 
	#Default 0.15
	#Range: 0.0 ~ 1.0
	battleSpawnChanceOnSpawnAttempt = 0.15
	#Determines the minimum starting wave for a battle. 
	#Default 1
	#Range: 0 ~ 999999999
	battleStartingWaveMin = 1
	#Determines the maximum starting wave for a battle. 
	#Default 5
	#Range: 0 ~ 999999999
	battleStartingWaveMax = 5
	#Base target strength of a faction battle. 
	#Will be divided over both factions. Default 45
	#Range: 0 ~ 9999
	factionBattleRaidTargetBaseStrengthPerWave = 45
	#Applied to the target strength of a faction battle. 
	#Multiplies the target strength and rounds down. Default 1.0F
	#Range: 0.0 ~ 100.0
	factionBattleRaidTargetStrengthMultiplier = 1.0

#Reconstruct Block Config
[reconstruct_block_config]
	#Enables Reconstruct Blocks 
	#Default True
	enableReconstructBlocks = true
	#Enables Reconstruct Blocks outside raids 
	#Default True
	enableReconstructBlocksOutsideRaids = true
	#Enables Reconstruct Blocks from the Gaia factions 
	#Default False
	enableReconstructBlocksFromGaia = false
	#Enables Reconstruct Blocks from players 
	#Default False
	enableReconstructBlocksFromPlayers = false
	#Reconstructs on loss 
	#Default false
	reconstructOnLoss = false
	#This value plus the variable version together make up the time required before reconstructing. 
	#Default 200
	#Range: 0 ~ 999999999
	reconstructTickDelay = 200
	#A random value between 0 and this value is added to the static delay to determine total delay. 
	#Default 200
	#Range: 0 ~ 999999999
	reconstructVariableTickDelay = 200

#AI Config
[ai_config]
	#Enables Digger AI and the spawning of diggers 
	#Default true
	enableDiggerAI = true

