#When a chest is generated in a supported structure it will have a 1/x chance of being a mimic. Higher value means fewer mimics. A value of 1 means always a mimic.
#Range: > 1
mimicSpawnChance = 5
#S: registry names of entities that should not have a displayed ToroHealth bar (ex. ["minecraft:wither", "minecraft:villager"]).
#Mimics are hard coded and will included while stealthed regardless of the list
#Since this is in the server config, all clients will be effected. Nothing will happen if ToroHealth is not installed
healthBarBlacklist = []

