
[Tables]
	#Customization slots allow you to enable the table to hold items (author doesn't like that so it's optional) or access nearby chests.
	#Range: 0 ~ 2
	"Simple table - number of customization slots" = 1
	#Customization slots allow you to enable the table to hold items (author doesn't like that so it's optional) or access nearby chests, or have lanterns as part of the table.
	#Range: 0 ~ 4
	"Dual table - number of customization slots" = 2
	#Here you can set which item allows you to access nearby inventories from a workbench window. Frankly there is no correct item here - customizations aren't upgrades, they are options - like checkboxes. This may delay availability of this functionality - you can put a minecraft:amethyst_shard if you want it to be available later in the game or a good old minecraft:torch if you want it available right away.
	"Customization - item for inventory access" = "minecraft:name_tag"
	#If set to false (default), simple crafting tables are craftable after you have vanilla crafting table. If set to true (not much reason not to be), this mod's crafting tables are craftable from four planks in 2x2 configuration.
	"Simple table replaces vanilla table" = false

[PotionShelf]
	#This is a multiplier for the number of bottles that fit in a single potion shelf slot. Default 6 (unrelated to six slots) means each slot can fit 6 non-stackable potions or for example 24 potions that stack up to 4 in players inventory.
	#Range: 1 ~ 12
	"Room in one potion shelf slot" = 6

[ToolRack]
	#If set to false, you need to move a tool from off-hand to main hand (F) before putting it onto a toolrack, it's simpler but needs extra actions. If you set this to true you can put tools from off-hand to toolrack directly and you can take items directly; quicker but there might be possible unintended interactions with the toolrack.
	"Offhand interacts with tool rack directly" = true

