
[general]

	[general.general]
		timestamps_format = 1
		streamer_mode = false
		modcore_warning = true
		essential_gui_scale = 4

	[general.online_status]
		show_essential_indicator_on_tab = true
		show_essential_indicator_on_nametags = true

	[general.experience]
		closer_placement_of_minimal_essential_menu = true
		darken_re-textured_menu_buttons = false
		essential_menu_layout = 1
		enable_essential = true
		use_vanilla_button_texture = true
		quick_action_bar = false

[hidden]

	[hidden.hidden]
		emote_perspective = 1
		coinspurchasecreatorcode = "__default__"
		screenshotbrowseritemsperrow = 3
		spspinnedgamerules = ""
		showemotepagekeybindbanner = true
		coinsselectedcurrency = "USD"

[emotes]

	[emotes.general]
		disable_emotes = false
		play_emotes_in_third_person_view = true
		emote_preview = false

[privacy]

	[privacy.general]
		display_current_server = true
		friend_privacy_settings = 0

[notifications]

	[notifications.general]
		disable_all_notifications = false
		host_world_ip_warning = false
		update_notifications = true
		screenshot_toast_duration = 1
		message_sound = true
		online_friend_alert = true
		message_notifications = true
		group_message_notifications = true

	[notifications.warnings]
		link_opening_warning = true

[quality_of_life]

	[quality_of_life.general]
		auto_refresh_session = true

	[quality_of_life.accessibility]
		enlarge_chat_metadata = true

	[quality_of_life.discord_integration]
		show_username_and_avatar = false
		set_activity_status_on_discord = false
		allow_ask_to_join = false
		show_current_server = false

	[quality_of_life.zoom]
		smooth_zoom_animation = false
		toggle_to_zoom = false
		smooth_camera_when_zoomed = false

	[quality_of_life.screenshots]
		vanilla_screenshot_message = false
		"screenshot_quick_action_#2_-_top_right" = 2
		"screenshot_quick_action_#3_-_bottom_left" = 0
		essential_screenshots = true
		screenshot_sounds = true
		"screenshot_quick_action_#1_-_top_left" = 5
		post_screenshot_action = 0
		"screenshot_quick_action_#4_-_bottom_right" = 4

[__meta]
	version = 11

[cosmetics]

	[cosmetics.general]
		hide_cosmetics_on_server_skins = false
		disable_cosmetics = false
		"cosmetic_&_armor_conflict_-_on_myself" = 0
		disable_cosmetics_in_inventory = false
		"cosmetic_&_armor_conflict_-_on_others" = 0

